version: '3'
services:
  minio:
    container_name: minio
    image: docker.io/bitnami/minio:2022
    privileged: true
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=MINIO
      - MINIO_ROOT_PASSWORD=RbCWAc9BRWsaHEYzCag7vFx3OWY06b7e
      - MINIO_DEFAULT_BUCKETS=ai-cloud-001
volumes:
  minio_data:
    driver: local