server:
  port: 8887
spring:
  datasource:
    url: jdbc:mysql://192.168.1.3:23306/ai_cloud_x?useUnicode=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true
    username: root
    password: PsOsGgN0rfXfIPbz
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: ai-resource
  servlet:
    multipart:
      max-request-size: 2000MB
      max-file-size: 2000MB
  data:
    web:
      pageable:
        page-parameter: current
        one-indexed-parameters: true
oss:
  bucket-name: ai-cloud-001
  name: minio
  endpoint: http://192.168.1.3:9000
  access-key: MINIO
  secret-key: RbCWAc9BRWsaHEYzCag7vFx3OWY06b7e
  enabled: true
  tenantMode: true
# 设置ribbon超时时间
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
feign:
  client:
    config:
      default:
        connectTimeout: 10000 #单位毫秒
        readTimeout: 60000 #单位毫秒
