server:
  port: 8887
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.3:38848
      metadata:
        preserved.heart.beat.interval: 1000 #心跳间隔。时间单位:毫秒。心跳间隔
        preserved.heart.beat.timeout: 3000 #心跳暂停。时间单位:毫秒。 即服务端6秒收不到客户端心跳，会将该客户端注册的实例设为不健康：
        preserved.ip.delete.timeout: 3000 #Ip删除超时。时间单位:毫秒。即服务端9秒收不到客户端心跳，会将该客户端注册的实例删除：
  application:
    name: ai-oss
  servlet:
    multipart:
      max-request-size: 2000MB
      max-file-size: 2000MB
  data:
    web:
      pageable:
        page-parameter: current
        one-indexed-parameters: true
mysql:
  default:
    url: jdbc:mysql://192.168.1.3:23305/ai_cloud_x?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: PsOsGgN0rfXfIPbz
    driverClassName: com.mysql.cj.jdbc.Driver
    packages:
      - org.qwb.ai.common.pojo
oss:
  bucket-name: ai-cloud-001
  name: minio
  endpoint: http://192.168.1.3:9000
  access-key: MINIO
  secret-key: RbCWAc9BRWsaHEYzCag7vFx3OWY06b7e
  enabled: true
  tenantMode: true
# 设置ribbon超时时间
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
feign:
  client:
    config:
      default:
        connectTimeout: 100000 #单位毫秒
        readTimeout: 600000 #单位毫秒
